# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'antibioticWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(632, 300)
        self.doseGetter = QtWidgets.QLineEdit(Form)
        self.doseGetter.setGeometry(QtCore.QRect(170, 90, 191, 22))
        self.doseGetter.setObjectName("doseGetter")
        self.lineEdit_6 = QtWidgets.QLineEdit(Form)
        self.lineEdit_6.setGeometry(QtCore.QRect(250, 220, 191, 22))
        self.lineEdit_6.setObjectName("lineEdit_6")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(150, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.p = QtWidgets.QLineEdit(Form)
        self.p.setGeometry(QtCore.QRect(110, 170, 191, 22))
        self.p.setObjectName("p")
        self.productNameGetter = QtWidgets.QLineEdit(Form)
        self.productNameGetter.setGeometry(QtCore.QRect(240, 130, 191, 22))
        self.productNameGetter.setObjectName("productNameGetter")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(40, 120, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(40, 160, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(40, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(40, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.buyButton_2 = QtWidgets.QPushButton(Form)
        self.buyButton_2.setGeometry(QtCore.QRect(520, 240, 93, 28))
        self.buyButton_2.setObjectName("buyButton_2")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_6.setText(_translate("Form", "Antibioticos"))
        self.label_8.setText(_translate("Form", "Nombre del producto"))
        self.label_9.setText(_translate("Form", "Precio"))
        self.label_10.setText(_translate("Form", "Animal para la dosis"))
        self.label_7.setText(_translate("Form", "Dosis"))
        self.buyButton_2.setText(_translate("Form", "Comprar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
