# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'fertilizerWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(627, 322)
        self.label = QtWidgets.QLabel(Form)
        self.label.setGeometry(QtCore.QRect(130, 20, 181, 21))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(Form)
        self.label_2.setGeometry(QtCore.QRect(20, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(Form)
        self.label_3.setGeometry(QtCore.QRect(20, 120, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.label_4 = QtWidgets.QLabel(Form)
        self.label_4.setGeometry(QtCore.QRect(20, 160, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.label_5 = QtWidgets.QLabel(Form)
        self.label_5.setGeometry(QtCore.QRect(20, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.ICAGetter = QtWidgets.QLineEdit(Form)
        self.ICAGetter.setGeometry(QtCore.QRect(150, 90, 191, 22))
        self.ICAGetter.setObjectName("ICAGetter")
        self.productNameGetter = QtWidgets.QLineEdit(Form)
        self.productNameGetter.setGeometry(QtCore.QRect(220, 130, 191, 22))
        self.productNameGetter.setObjectName("productNameGetter")
        self.priceGetter = QtWidgets.QLineEdit(Form)
        self.priceGetter.setGeometry(QtCore.QRect(90, 170, 191, 22))
        self.priceGetter.setObjectName("priceGetter")
        self.frequencyApplicationGetter = QtWidgets.QLineEdit(Form)
        self.frequencyApplicationGetter.setGeometry(QtCore.QRect(250, 220, 191, 22))
        self.frequencyApplicationGetter.setObjectName("frequencyApplicationGetter")
        self.lastApplicationGetter = QtWidgets.QLineEdit(Form)
        self.lastApplicationGetter.setGeometry(QtCore.QRect(250, 270, 191, 22))
        self.lastApplicationGetter.setText("")
        self.lastApplicationGetter.setObjectName("lastApplicationGetter")
        self.label_6 = QtWidgets.QLabel(Form)
        self.label_6.setGeometry(QtCore.QRect(20, 260, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.buyButton = QtWidgets.QPushButton(Form)
        self.buyButton.setGeometry(QtCore.QRect(520, 270, 93, 28))
        self.buyButton.setObjectName("buyButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label.setText(_translate("Form", "Fertilizantes"))
        self.label_2.setText(_translate("Form", "Registro ICA"))
        self.label_3.setText(_translate("Form", "Nombre del producto"))
        self.label_4.setText(_translate("Form", "Precio"))
        self.label_5.setText(_translate("Form", "Frecuencia de aplicacion"))
        self.label_6.setText(_translate("Form", "Ultima aplicacion"))
        self.buyButton.setText(_translate("Form", "Comprar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
