# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'mainWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(987, 487)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(220, 90, 541, 141))
        font = QtGui.QFont()
        font.setPointSize(48)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.searchByIDButtom = QtWidgets.QPushButton(self.centralwidget)
        self.searchByIDButtom.setGeometry(QtCore.QRect(140, 310, 211, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.searchByIDButtom.setFont(font)
        self.searchByIDButtom.setObjectName("searchByIDButtom")
        self.buyProductsButtom = QtWidgets.QPushButton(self.centralwidget)
        self.buyProductsButtom.setGeometry(QtCore.QRect(560, 310, 271, 51))
        font = QtGui.QFont()
        font.setPointSize(18)
        self.buyProductsButtom.setFont(font)
        self.buyProductsButtom.setObjectName("buyProductsButtom")
        MainWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "Tienda agricola "))
        self.searchByIDButtom.setText(_translate("MainWindow", "Mis facturas"))
        self.buyProductsButtom.setText(_translate("MainWindow", "Comprar productos"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    MainWindow = QtWidgets.QMainWindow()
    ui = Ui_MainWindow()
    ui.setupUi(MainWindow)
    MainWindow.show()
    sys.exit(app.exec_())
