# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'plagueControlWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Form(object):
    def setupUi(self, Form):
        Form.setObjectName("Form")
        Form.resize(621, 322)
        self.label_12 = QtWidgets.QLabel(Form)
        self.label_12.setGeometry(QtCore.QRect(30, 260, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_12.setFont(font)
        self.label_12.setObjectName("label_12")
        self.label_7 = QtWidgets.QLabel(Form)
        self.label_7.setGeometry(QtCore.QRect(140, 20, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(14)
        self.label_7.setFont(font)
        self.label_7.setObjectName("label_7")
        self.label_8 = QtWidgets.QLabel(Form)
        self.label_8.setGeometry(QtCore.QRect(30, 80, 121, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.label_11 = QtWidgets.QLabel(Form)
        self.label_11.setGeometry(QtCore.QRect(30, 210, 221, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_11.setFont(font)
        self.label_11.setObjectName("label_11")
        self.label_9 = QtWidgets.QLabel(Form)
        self.label_9.setGeometry(QtCore.QRect(30, 120, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_9.setFont(font)
        self.label_9.setObjectName("label_9")
        self.priceGetter = QtWidgets.QLineEdit(Form)
        self.priceGetter.setGeometry(QtCore.QRect(100, 170, 191, 22))
        self.priceGetter.setObjectName("priceGetter")
        self.ICAGetter = QtWidgets.QLineEdit(Form)
        self.ICAGetter.setGeometry(QtCore.QRect(160, 90, 191, 22))
        self.ICAGetter.setObjectName("ICAGetter")
        self.productNameGetter = QtWidgets.QLineEdit(Form)
        self.productNameGetter.setGeometry(QtCore.QRect(230, 130, 191, 22))
        self.productNameGetter.setObjectName("productNameGetter")
        self.frequencyApplicationGetter = QtWidgets.QLineEdit(Form)
        self.frequencyApplicationGetter.setGeometry(QtCore.QRect(260, 220, 191, 22))
        self.frequencyApplicationGetter.setObjectName("frequencyApplicationGetter")
        self.label_10 = QtWidgets.QLabel(Form)
        self.label_10.setGeometry(QtCore.QRect(30, 160, 191, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_10.setFont(font)
        self.label_10.setObjectName("label_10")
        self.gracePeriodGetter = QtWidgets.QLineEdit(Form)
        self.gracePeriodGetter.setGeometry(QtCore.QRect(260, 270, 191, 22))
        self.gracePeriodGetter.setText("")
        self.gracePeriodGetter.setObjectName("gracePeriodGetter")
        self.buyButton = QtWidgets.QPushButton(Form)
        self.buyButton.setGeometry(QtCore.QRect(520, 260, 93, 28))
        self.buyButton.setObjectName("buyButton")

        self.retranslateUi(Form)
        QtCore.QMetaObject.connectSlotsByName(Form)

    def retranslateUi(self, Form):
        _translate = QtCore.QCoreApplication.translate
        Form.setWindowTitle(_translate("Form", "Form"))
        self.label_12.setText(_translate("Form", "Periodo de carencia"))
        self.label_7.setText(_translate("Form", "Control de plagas"))
        self.label_8.setText(_translate("Form", "Registro ICA"))
        self.label_11.setText(_translate("Form", "Frecuencia de aplicacion"))
        self.label_9.setText(_translate("Form", "Nombre del producto"))
        self.label_10.setText(_translate("Form", "Precio"))
        self.buyButton.setText(_translate("Form", "Comprar"))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    Form = QtWidgets.QWidget()
    ui = Ui_Form()
    ui.setupUi(Form)
    Form.show()
    sys.exit(app.exec_())
