# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'searchByIdWindow.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_searchWindow(object):
    def setupUi(self, searchWindow):
        searchWindow.setObjectName("searchWindow")
        searchWindow.resize(638, 137)
        self.centralwidget = QtWidgets.QWidget(searchWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.idGetter_2 = QtWidgets.QLineEdit(self.centralwidget)
        self.idGetter_2.setGeometry(QtCore.QRect(290, 60, 161, 22))
        self.idGetter_2.setObjectName("idGetter_2")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(10, 50, 271, 31))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        searchWindow.setCentralWidget(self.centralwidget)
        self.statusbar = QtWidgets.QStatusBar(searchWindow)
        self.statusbar.setObjectName("statusbar")
        searchWindow.setStatusBar(self.statusbar)

        self.retranslateUi(searchWindow)
        QtCore.QMetaObject.connectSlotsByName(searchWindow)

    def retranslateUi(self, searchWindow):
        _translate = QtCore.QCoreApplication.translate
        searchWindow.setWindowTitle(_translate("searchWindow", "MainWindow"))
        self.label_2.setText(_translate("searchWindow", "Digite la cedula de la persona "))


if __name__ == "__main__":
    import sys
    app = QtWidgets.QApplication(sys.argv)
    searchWindow = QtWidgets.QMainWindow()
    ui = Ui_searchWindow()
    ui.setupUi(searchWindow)
    searchWindow.show()
    sys.exit(app.exec_())
